# Generated by Django 6.0.1 on 2026-01-24 21:01

from django.db import migrations, models
import docpond.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoclingPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqid', docpond.fields.ModelSeedSqidsField(editable=False, min_length=4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(help_text='Preset name', max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default preset')),
                ('pipeline_type', models.CharField(choices=[('standard', 'Standard PDF Pipeline'), ('vlm', 'Vision-Language Model Pipeline')], default='standard', help_text='Pipeline type: standard PDF or VLM', max_length=20)),
                ('ocr_engine', models.CharField(choices=[('auto', 'Auto (Best Available)'), ('easyocr', 'EasyOCR'), ('tesseract', 'Tesseract CLI'), ('rapidocr', 'RapidOCR'), ('ocrmac', 'macOS Vision OCR')], default='auto', help_text='OCR engine to use', max_length=20)),
                ('force_ocr', models.BooleanField(default=False, help_text='Force full page OCR even for PDFs with text')),
                ('ocr_languages', models.JSONField(blank=True, default=list, help_text='List of language codes for OCR (format depends on OCR engine)')),
                ('vlm_model', models.CharField(blank=True, default='', help_text="VLM model repo ID (e.g., 'ibm-granite/granite-docling-258M')", max_length=200)),
                ('enable_picture_description', models.BooleanField(default=False, help_text='Generate descriptions for images using VLM')),
                ('picture_description_prompt', models.TextField(blank=True, default='Describe this image in a few sentences.', help_text='Prompt for picture description model')),
                ('enable_table_structure', models.BooleanField(default=True, help_text='Enable table structure extraction')),
                ('table_former_mode', models.CharField(choices=[('fast', 'Fast Mode'), ('accurate', 'Accurate Mode')], default='accurate', help_text='TableFormer extraction mode', max_length=20)),
                ('enable_code_enrichment', models.BooleanField(default=False, help_text='Enable specialized processing for code blocks')),
                ('enable_formula_enrichment', models.BooleanField(default=False, help_text='Enable LaTeX formula recognition')),
                ('filter_orphan_clusters', models.BooleanField(default=False, help_text='Filter out orphaned text clusters (e.g., page numbers, headers)')),
                ('filter_empty_clusters', models.BooleanField(default=True, help_text='Filter out empty clusters in layout')),
                ('advanced_settings', models.JSONField(blank=True, default=dict, help_text='Advanced pipeline options in JSON format')),
            ],
            options={
                'verbose_name': 'Docling Preset',
                'verbose_name_plural': 'Docling Presets',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]

