# Generated by Django 6.0.1 on 2026-01-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcrPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(help_text='Preset name', max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default preset')),
                ('force_ocr', models.BooleanField(default=False, help_text='Force OCR even if document already contains text')),
                ('skip_text', models.BooleanField(default=False, help_text='Skip OCR on pages that already have text')),
                ('redo_ocr', models.BooleanField(default=False, help_text='Remove existing OCR and redo it')),
                ('ocr_backend', models.CharField(choices=[('tesseract', 'Tesseract'), ('cuneiform', 'Cuneiform'), ('easyocr', 'EasyOCR')], default='tesseract', help_text='OCR engine to use', max_length=20)),
                ('language', models.CharField(default='eng', help_text="OCR language code (e.g., 'eng', 'nld', 'eng+nld')", max_length=50)),
                ('optimize', models.IntegerField(choices=[(0, 'No optimization'), (1, 'Lossless'), (2, 'Lossy'), (3, 'Aggressive')], default=1, help_text='PDF optimization level')),
                ('jpeg_quality', models.IntegerField(default=75, help_text='JPEG quality for images (1-100)')),
                ('png_quality', models.IntegerField(default=70, help_text='PNG quality for images (1-100)')),
                ('deskew', models.BooleanField(default=False, help_text='Deskew pages before OCR')),
                ('clean', models.BooleanField(default=False, help_text='Clean pages before OCR (removes background noise)')),
                ('clean_final', models.BooleanField(default=False, help_text='Clean pages after OCR')),
                ('remove_background', models.BooleanField(default=False, help_text='Remove background from pages')),
                ('oversample', models.IntegerField(default=0, help_text='Oversample images to at least this DPI (0 = no oversampling)')),
                ('rotate_pages', models.BooleanField(default=False, help_text='Rotate pages to correct orientation')),
                ('remove_vectors', models.BooleanField(default=False, help_text='Remove vector graphics from PDF')),
                ('advanced_settings', models.JSONField(blank=True, default=dict, help_text='Additional OCRmyPDF arguments in JSON format')),
            ],
            options={
                'verbose_name': 'OCR Preset',
                'verbose_name_plural': 'OCR Presets',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
