# Generated by Django 6.0.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_presets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocrpreset',
            old_name='clean',
            new_name='do_clean',
        ),
        migrations.RenameField(
            model_name='ocrpreset',
            old_name='clean_final',
            new_name='do_clean_final',
        ),
    ]

