# Generated by Django 6.0.1 on 2026-01-23 15:46

import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ponds', '0001_initial'),
    ]
    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='DoclingPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(help_text='Preset name', max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default preset')),
                ('pipeline_type', models.CharField(choices=[('standard', 'Standard PDF Pipeline'), ('vlm', 'Vision-Language Model Pipeline')], default='standard', help_text='Pipeline type: standard PDF or VLM', max_length=20)),
                ('ocr_engine', models.CharField(choices=[('auto', 'Auto (Best Available)'), ('easyocr', 'EasyOCR'), ('tesseract', 'Tesseract CLI'), ('rapidocr', 'RapidOCR'), ('ocrmac', 'macOS Vision OCR')], default='auto', help_text='OCR engine to use', max_length=20)),
                ('force_ocr', models.BooleanField(default=False, help_text='Force full page OCR even for PDFs with text')),
                ('ocr_languages', models.JSONField(blank=True, default=list, help_text='List of language codes for OCR (format depends on OCR engine)')),
                ('vlm_model', models.CharField(blank=True, default='', help_text="VLM model repo ID (e.g., 'ibm-granite/granite-docling-258M')", max_length=200)),
                ('enable_picture_description', models.BooleanField(default=False, help_text='Generate descriptions for images using VLM')),
                ('picture_description_prompt', models.TextField(blank=True, default='Describe this image in a few sentences.', help_text='Prompt for picture description model')),
                ('enable_table_structure', models.BooleanField(default=True, help_text='Enable table structure extraction')),
                ('table_former_mode', models.CharField(choices=[('fast', 'Fast Mode'), ('accurate', 'Accurate Mode')], default='accurate', help_text='TableFormer extraction mode', max_length=20)),
                ('enable_code_enrichment', models.BooleanField(default=False, help_text='Enable specialized processing for code blocks')),
                ('enable_formula_enrichment', models.BooleanField(default=False, help_text='Enable LaTeX formula recognition')),
                ('filter_orphan_clusters', models.BooleanField(default=False, help_text='Filter out orphaned text clusters (e.g., page numbers, headers)')),
                ('filter_empty_clusters', models.BooleanField(default=True, help_text='Filter out empty clusters in layout')),
                ('advanced_settings', models.JSONField(blank=True, default=dict, help_text='Advanced pipeline options in JSON format')),
            ],
            options={
                'verbose_name': 'Docling Preset',
                'verbose_name_plural': 'Docling Presets',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=documents.models.thumbnail_upload_path)),
                ('original_pdf', models.FileField(upload_to=documents.models.document_upload_path)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_pages', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('docling_preset', models.ForeignKey(blank=True, help_text='Docling preset to use for processing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.doclingpreset')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ponds.pond')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('page_number', models.PositiveIntegerField()),
                ('page_pdf', models.FileField(upload_to=documents.models.page_upload_path)),
                ('ocr_markdown_raw', models.TextField(blank=True)),
                ('text_markdown_clean', models.TextField(blank=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ocr_references', models.JSONField(blank=True, null=True)),
                ('bbox_visualization', models.ImageField(blank=True, null=True, upload_to=documents.models.bbox_visualization_upload_path)),
                ('docling_json', models.JSONField(blank=True, help_text='Original docling JSON output', null=True)),
                ('docling_json_override', models.JSONField(blank=True, help_text='Corrected/overridden docling JSON data', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image_file', models.ImageField(height_field='height', upload_to=documents.models.image_upload_path, width_field='width')),
                ('caption', models.TextField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='documents.page')),
            ],
            options={
                'abstract': False,
            },
        ),

    ]
