# Generated by Django 6.0.1 on 2026-01-17 09:47

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoclingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('ocr_engine', models.CharField(choices=[('tesseract', 'Tesseract'), ('easyocr', 'EasyOCR'), ('doctr', 'DocTR')], default='tesseract', max_length=50)),
                ('detect_tables', models.BooleanField(default=True)),
                ('detect_figures', models.BooleanField(default=True)),
                ('ignore_headers_footers', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('confidence_threshold', models.FloatField(default=0.7)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Docling Settings',
                'verbose_name_plural': 'Docling Settings',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=documents.models.thumbnail_upload_path)),
                ('original_pdf', models.FileField(upload_to=documents.models.document_upload_path)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_pages', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='groups.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('page_number', models.PositiveIntegerField()),
                ('page_pdf', models.FileField(upload_to=documents.models.page_upload_path)),
                ('ocr_markdown_raw', models.TextField(blank=True)),
                ('text_markdown_clean', models.TextField(blank=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('docling_layout', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image_file', models.FileField(upload_to=documents.models.image_upload_path)),
                ('caption', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='documents.page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
