# Generated by Django 6.0.1 on 2026-01-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='bbox_visualization',
        ),
        migrations.RemoveField(
            model_name='page',
            name='ocr_references',
        ),
    ]
