# Generated by Django 6.0.1 on 2026-01-24 16:39

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_page_bbox_visualization_and_more'),
        ('ocr_presets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_preset',
            field=models.ForeignKey(blank=True, help_text='OCR preset to use for preprocessing (runs before page splitting)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='ocr_presets.ocrpreset'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_image',
            field=models.ImageField(blank=True, help_text='Preview image of the page', null=True, upload_to=documents.models.page_image_upload_path),
        ),
    ]
