# Generated by Django 6.0.1 on 2026-01-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_create_default_docling_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doclingsettings',
            name='output_format',
        ),
    ]
