# Generated by Django 6.0.1 on 2026-01-16 21:17

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_doclingsettings_output_format'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
