# Generated by Django 6.0.1 on 2026-01-24 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docling_presets', '0001_initial'),
        ('documents', '0003_document_ocr_preset_page_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docling_preset',
            field=models.ForeignKey(blank=True, help_text='Docling preset to use for processing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='docling_presets.doclingpreset'),
        ),
        migrations.DeleteModel(
            name='DoclingPreset',
        ),
    ]
