# Generated by Django 6.0.1 on 2026-01-20 20:47

import documents.models
from django.db import migrations, models


# Define upload path locally since it was moved to images app
def local_image_upload_path(instance, filename):
    """Generate upload path for extracted images: /{group}/{book-name}/{page-number}/images/{image-id}.jpg"""
    group_name = instance.page.document.group.name
    clean_title = "".join(c for c in instance.page.document.title if c.isalnum() or c in (' ', '-', '_')).rstrip()
    return f"{group_name}/{clean_title}/{instance.page.page_number}/images/{filename}"


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_rename_to_deepseek_ocr_and_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(height_field='height_field', upload_to=local_image_upload_path, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='page',
            name='bbox_visualization',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.bbox_visualization_upload_path),
        ),
    ]
