# Generated by Django 6.0.1 on 2026-01-20 20:47

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_rename_to_deepseek_ocr_and_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(height_field='height_field', upload_to=documents.models.image_upload_path, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='page',
            name='bbox_visualization',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.bbox_visualization_upload_path),
        ),
    ]
