# Generated by Django 6.0.1 on 2026-01-20 20:48

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_image_image_file_alter_page_bbox_visualization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='bbox_visualization',
            field=models.ImageField(blank=True, null=True, upload_to=documents.models.bbox_visualization_upload_path),
        ),
    ]
