# Generated by Django 6.0.1 on 2026-01-20 20:51

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_page_bbox_visualization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(height_field='height', upload_to=documents.models.image_upload_path, width_field='width'),
        ),
    ]
