# Generated by Django 6.0.1 on 2026-01-20 20:51

import documents.models
from django.db import migrations, models


# Define upload path locally since it was moved to images app
def local_image_upload_path(instance, filename):
    """Generate upload path for extracted images: /{group}/{book-name}/{page-number}/images/{image-id}.jpg"""
    group_name = instance.page.document.group.name
    clean_title = "".join(c for c in instance.page.document.title if c.isalnum() or c in (' ', '-', '_')).rstrip()
    return f"{group_name}/{clean_title}/{instance.page.page_number}/images/{filename}"


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_page_bbox_visualization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(height_field='height', upload_to=local_image_upload_path, width_field='width'),
        ),
    ]
