# Generated by Django 6.0.1 on 2026-01-20 21:52

import django.db.models.deletion
import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0009_remove_image_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image_file', models.ImageField(height_field='height', upload_to=images.models.image_upload_path, width_field='width')),
                ('alt_text', models.TextField(blank=True, help_text='AI-generated alt text for the image', null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='documents.page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
